### ISSUE TITLE
Undefined function or variable 'w2R'.

### ISSUE THREAD

**Issue by urbste** [pulak09/NeuRoRA#1]
Hi,

thanks for sharing the code!
I am missing a function w2R if I excecute the script Example_generate_data_pytourch.m.
Matlab error: Undefined function or variable 'w2R'.

Regards
Steffen

**Comment by urbste** [comment]
I found it in the zip file SO3GraphAveraging.PAMI.rar here: http://www.ee.iisc.ac.in/labs/cvl/research/rotaveraging/

Btw same error later with function R2w.m

**Comment by pulak09** [comment]
Hi Steffen,

I have uploaded the file. Thanks for letting me know about the missing file and sorry for the late response. 

Cheers,
Pulak
